---
# Too picky.
Metrics/LineLength:
  Enabled: false

# This should truly be on for well documented gems.
Style/Documentation:
  Enabled: false

# Neatly aligned code is to swell.
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Rubocop default is leading but hound-ci use trailing.
Style/DotPosition:
  EnforcedStyle: leading

# Don't mess with RSpec DSL.
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

# We really like the readability with newline in beginning of classes.
Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
